root:
  common: 
    PGHOST: 'postgres_ml'
    svmCost: 100
    svmNuDefault: 0.556015
    offset: 50
    limit: 480
    cv: 10
    dataminestocksViewName: "v2.dataminestocks_py"
    startNu: 0.00000001
    initialStepNu: 0.1
    FEATURESELECTIONDATASETLENGTH: 300
    DATASETLENGTH: 2000
    GAMMACOSTDATASETLENGTH: 5000
    FITDATASETLENGTH: 6000
    TESTDATASETLENGTH: 100
    PREDICTATASETLENGTH: 100
    isUseCache: True
    LSLIB: "libsvm-3.21"
    # LSLIB: "libsvm-3.17-GPU_x64-linux-v1.2"
    #dbnameConst: "dataminestocks1"
    dbnameConst: "postgres"
  trdeindicators:
    futureShiftDays: 30
    difftreshhold: 0.02
    upper: 1.02
    lower: 0.98
